[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://caboose.proxy.rlwy.net:16904/:splat"
  status = 200
  force = true
